### PR TITLE
Implement TranitioningContentControl-demo

### LINKED ISSUE #200: Docs for the TransitioningContentControl needed

### PR DESCRIPTION
**Pull request by timunie**
Hey Avalonia-team, 

I've implemented some videos for showing the result. I am not sure if they will be available in your docs. Can we somehow test this before merging this PR?

Closes #200

### CODE REVIEW

**Review by Arhell — APPROVED** [review]

**Comment by timunie** [comment]
Hi @Arhell ,

Were you able to check if the videos work with gitbook? I was not able to test. 

Thank you and have a great Sunday
Tim

**Comment by maxkatz6** [comment]
Let's merge and see how it's displayed. Hard to guess otherwise.

**Comment by maxkatz6** [comment]
Okay, seems it doesn't work.
Gitbook supports only youtube videos embeding as I understood: https://docs.gitbook.com/editing-content/embeds
Wouldn't it be easier to use a gif instead?

**Comment by timunie** [comment]
> Okay, seems it doesn't work. Gitbook supports only youtube videos embeding as I understood: https://docs.gitbook.com/editing-content/embeds Wouldn't it be easier to use a gif instead?

Allright, was worth a try, The reason was I wanted to reduce the file size, as there are not many common pixels which makes the file larger. 

I'll update this in the next days.

**Pull request merged**
