### PR TITLE
Update docs to reflect Avalonia.NameGenerator is now included with templates

### PR DESCRIPTION
**Pull request by DmitriyYukhanov**
This method is now placed at the Window.cs.

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=227) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=227) before we can accept your contribution.<br/><br/>:x: DmitriyYukhanov [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=227)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Documentation?pullRequest=227) it.</sub>

**Review by Arhell — APPROVED** [review]

**Comment by maxkatz6** [comment]
I am a bit conflicted about it, because InitiateComponent is still required, if developers don't use [Avalonia.NameGenerator](https://github.com/AvaloniaUI/Avalonia.NameGenerator) (included now by default with templates).
Should there be at least a note to mention it?

**Comment by maxkatz6** [comment]
Also when name generator is used, "partial" modifier must be set on classes. Should be added to avoid confusion if developers will copy-paste this code.

**Comment by DmitriyYukhanov** [comment]
> I am a bit conflicted about it, because InitializeComponent is still required, if developers don't use [Avalonia.NameGenerator](https://github.com/AvaloniaUI/Avalonia.NameGenerator) (included now by default with templates). Should there be at least a note to mention it?

Thank you for taking a look @maxkatz6, all the good valid points!
Shame on me, I even didn't know about NameGenerator 😅
Would like to sync on how would you prefer to see it mentioned before committing any further changes. How something like this would work for you?

```csharp
using Avalonia;
using Avalonia.Controls;
using Avalonia.Interactivity;
using Avalonia.Markup.Xaml;

namespace AvaloniaApplication1
{
    public partial class MainWindow : Window
    {
        public MainWindow()
        {
            // this method body is generated with Avalonia.NameGenerator
            InitializeComponent();
        }

        public void button_Click(object sender, RoutedEventArgs e)
        {
            // Change button text when button is clicked.
            var button = (Button)sender;
            button.Content = "Hello, Avalonia!";
        }
    }
}
```

**Comment by maxkatz6** [comment]
> How something like this would work for you?

Yes, looks good to me.

**Comment by DmitriyYukhanov** [comment]
Alright, I've gone a step forward and updated docs to reflect Avalonia.NameGenerator package is now included with the templates.

**Pull request merged**
