### PR TITLE
Fix install command

### PR DESCRIPTION
**Pull request by dodbrian**
## What does the pull request do?
Fix a typo in the documentation

**Scope of this PR:**
- [x] fix or update to an existing page

## Checklist

**In any case**
- [x] Spell-checking done
- [x] Checked if all hyperlinks work
- [x] Checked if all images are visible

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=376) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=376) before we can accept your contribution.<br/><br/>:x: dodbrian [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=376)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Documentation?pullRequest=376) it.</sub>

**Comment by maxkatz6** [comment]
That's not a typo. See https://github.com/AvaloniaUI/Documentation/pull/373

**Comment by maxkatz6** [comment]
Possibly some side note should be added for the older SDKs.

**Comment by dodbrian** [comment]
@maxkatz6 I've added a remark. Please review.

**Review by maxkatz6 — APPROVED** [review]

**Comment by maxkatz6** [comment]
@dodbrian thanks!
Can you sign CLA from the first comment? https://github.com/AvaloniaUI/Documentation/pull/376#issuecomment-1329405097

**Review by Arhell — APPROVED** [review]

**Comment by dodbrian** [comment]
> @dodbrian thanks! Can you sign CLA from the first comment? [#376 (comment)](https://github.com/AvaloniaUI/Documentation/pull/376#issuecomment-1329405097)

@maxkatz6 I try to sign but alway get the following error:

```
MongoTopologyClosedError: Topology is closed
    at processWaitQueue (/home/site/wwwroot/node_modules/mongodb/lib/sdam/topology.js:608:46)
    at Topology.selectServer (/home/site/wwwroot/node_modules/mongodb/lib/sdam/topology.js:317:9)
    at /home/site/wwwroot/node_modules/mongodb/lib/operations/execute_operation.js:18:29
    at maybePromise (/home/site/wwwroot/node_modules/mongodb/lib/utils.js:496:5)
    at executeOperation (/home/site/wwwroot/node_modules/mongodb/lib/operations/execute_operation.js:16:37)
    at FindCursor._initialize (/home/site/wwwroot/node_modules/mongodb/lib/cursor/find_cursor.js:54:50)
    at next (/home/site/wwwroot/node_modules/mongodb/lib/cursor/abstract_cursor.js:445:16)
    at /home/site/wwwroot/node_modules/mongodb/lib/cursor/abstract_cursor.js:177:13
    at maybePromise (/home/site/wwwroot/node_modules/mongodb/lib/utils.js:496:5)
    at FindCursor.next (/home/site/wwwroot/node_modules/mongodb/lib/cursor/abstract_cursor.js:173:41)
    at Collection.findOne (/home/site/wwwroot/node_modules/mongodb/lib/collection.js:232:76)
    at /home/site/wwwroot/node_modules/connect-mongo/build/main/lib/MongoStore.js:207:50
```

**Pull request merged**
