### PR TITLE
Updated Jaya File Manager details.

### PR DESCRIPTION
**Pull request by waliarubal**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=315) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=315) before we can accept your contribution.<br/><br/>:x: waliarubal [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=315)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Documentation?pullRequest=315) it.</sub>

**Comment by jmacato** [comment]
@waliarubal just curious, is Jaya still in active development? last commit i saw there is more than a year ago already?

**Comment by waliarubal** [comment]
Yes @jmacato , I have resumed work on this project again after an year. Doing a complete rewrite in dev-v3 branch of it. I was busy for whole year in relocating from India to Canada. We moved to Canada last month so finally I am sitting back to revive this project.

To answer your question, yes its still in development. Once the dev-v3 branch becomes stable enough, I'll make it the default branch.

**Comment by jmacato** [comment]
Awesome :D That's a great news :+1:

**Review by jmacato — APPROVED** [review]

**Pull request merged**
