### PR TITLE
Add documentation for TrayIcon

### PR DESCRIPTION
**Pull request by Ombrelin**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=313) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=313) before we can accept your contribution.<br/><br/>:x: Ombrelin [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=313)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Documentation?pullRequest=313) it.</sub>

**Review by Arhell — COMMENTED** [review]
сс @maxkatz6

**Review by jmacato — CHANGES_REQUESTED** [review]

**Review by jmacato — APPROVED** [review]

**Comment by timunie** [comment]
@jmacato @Arhell probably you forgot to update the outline. The page is not there in the docs.

**Comment by timunie** [comment]
> @jmacato @Arhell probably you forgot to update the outline. The page is not there in the docs.

Added, see #318

**Pull request merged**
