### PR TITLE
Update to bindings.ms - Missing handlebars

### PR DESCRIPTION
**Pull request by ApiumJacob**

### CODE REVIEW

**Comment by dnfadmin** [comment]
[CLA assistant check](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=350) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=350) before we can accept your contribution.<br/><br/>:x: ApiumJacob [sign now](https://cla.dotnetfoundation.org/AvaloniaUI/Documentation?pullRequest=350)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.dotnetfoundation.org/check/AvaloniaUI/Documentation?pullRequest=350) it.</sub>

**Comment by maxkatz6** [comment]
@ApiumJacob you need to sign the CLA, link is in that comment from the bot

**Review by Arhell — APPROVED** [review]

**Comment by ApiumJacob** [comment]
Yeah, next time I'll use my personal github so I can sign the CLA without issue.

**Review by jmacato — APPROVED** [review]

**Comment by maxkatz6** [comment]
We can't merge PRs without signed CLA.
But I fixed the typo with my commit.
@ApiumJacob thanks for noticing this typo!

**Pull request closed without merging**
